name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: Build using Visual Studio
      if: matrix.platform == 'windows-latest'
      run: ./build_vs.bat
    - name: Build using Unix Makefiles
      if: matrix.platform == 'ubuntu-latest'
      run: |
        chmod +x ./build_make.sh
        ./build_make.sh
    - name: Build using Xcode
      if: matrix.platform == 'macos-latest'
      run: |
        chmod +x ./build_xcode.sh
        ./build_xcode.sh
